import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import localFont from "next/font/local";

import { gsap } from "gsap";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { ScrollSmoother } from "gsap/dist/ScrollSmoother";

const urwForm = localFont({
  src: [
    {
      path: "../../../public/fonts/URWForm-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/URWForm-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../../public/fonts/URWForm-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-urwForm",
  preload: true,
  display: "swap",
});

// const arabicFont = localFont({
//   src: [
//     {
//       path: "../../public/fonts/Tajawal-Regular.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../../public/fonts/Tajawal-Bold.woff2",
//       weight: "700",
//       style: "normal",
//     },
//   ],
//   variable: "--font-arabic",
//   preload: true,
//   display: "swap",
// });

export const metadata = {
  title: "Yangwang",
  description: "Generated by create next app",
};

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger, ScrollSmoother, useGSAP);
}

export default async function RootLayout({ children, params }) {
  const { lang } = await params;
  console.log("lang root", lang);

  const isEnglish = true;

  return (
    <html lang={lang} dir={lang === "en" ? "ltr" : "rtl"} className="">
      <body className={`${urwForm.variable} antialiased min-h-screen flex flex-col rtl:text-right rtl:[direction:rtl;]`}>
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
