import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import localFont from "next/font/local";

import { gsap } from "gsap";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { ScrollSmoother } from "gsap/dist/ScrollSmoother";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import Script from "next/script";
import PageTransition from "@/components/common/PageTransition";

const urwForm = localFont({
  src: [
    {
      path: "../../../public/fonts/URWForm-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/URWForm-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../../public/fonts/URWForm-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-urwForm",
  preload: true,
  display: "swap",
});

// const arabicFont = localFont({
//   src: [
//     {
//       path: "../../../public/fonts/Tajawal-Regular.ttf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../../../public/fonts/Tajawal-Bold.ttf",
//       weight: "700",
//       style: "normal",
//     },
//   ],
//   variable: "--font-arabic",
//   preload: true,
//   display: "swap",
// });

export const metadata = {
  title: "Yangwang",
  description: "Generated by create next app",
};

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger, ScrollSmoother, useGSAP);
}

async function getMessages(locale) {
  try {
    return (await import(`../../../messages/${locale}.json`)).default;
  } catch (error) {
    console.error(
      `[2025-05-29T12:10:00.000Z] Failed to load messages for ${locale}:`,
      error.message
    );
    notFound();
  }
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages(locale);

  return (
    // <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} className={`${urwForm.variable} ${arabicFont.variable}`}>
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${urwForm.variable} antialiased min-h-screen flex flex-col rtl:text-right rtl:[direction:rtl;]`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header locale={locale} />
          {/* <main className="flex-grow">{children}</main> */}
          <PageTransition>{children}</PageTransition>
          <Footer locale={locale} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
